# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nchat.proto\"\x06\n\x04Nada\"/\n\x07Mensaje\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x11\n\tcontenido\x18\x03 \x01(\t2M\n\nServerChat\x12\x1f\n\nChatStream\x12\x05.Nada\x1a\x08.Mensaje0\x01\x12\x1e\n\x0bSendMessage\x12\x08.Mensaje\x1a\x05.Nadab\x06proto3')
)




_NADA = _descriptor.Descriptor(
  name='Nada',
  full_name='Nada',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=20,
)


_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Mensaje.timestamp', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='contenido', full_name='Mensaje.contenido', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['Nada'] = _NADA
DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Nada = _reflection.GeneratedProtocolMessageType('Nada', (_message.Message,), {
  'DESCRIPTOR' : _NADA,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Nada)
  })
_sym_db.RegisterMessage(Nada)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJE,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensaje)
  })
_sym_db.RegisterMessage(Mensaje)



_SERVERCHAT = _descriptor.ServiceDescriptor(
  name='ServerChat',
  full_name='ServerChat',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=71,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='ChatStream',
    full_name='ServerChat.ChatStream',
    index=0,
    containing_service=None,
    input_type=_NADA,
    output_type=_MENSAJE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='ServerChat.SendMessage',
    index=1,
    containing_service=None,
    input_type=_MENSAJE,
    output_type=_NADA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERCHAT)

DESCRIPTOR.services_by_name['ServerChat'] = _SERVERCHAT

# @@protoc_insertion_point(module_scope)
