# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ServerChatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ChatStream = channel.unary_stream(
        '/ServerChat/ChatStream',
        request_serializer=chat__pb2.Nada.SerializeToString,
        response_deserializer=chat__pb2.Mensaje.FromString,
        )
    self.SendMessage = channel.unary_unary(
        '/ServerChat/SendMessage',
        request_serializer=chat__pb2.Mensaje.SerializeToString,
        response_deserializer=chat__pb2.Nada.FromString,
        )


class ServerChatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ChatStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendMessage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerChatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ChatStream': grpc.unary_stream_rpc_method_handler(
          servicer.ChatStream,
          request_deserializer=chat__pb2.Nada.FromString,
          response_serializer=chat__pb2.Mensaje.SerializeToString,
      ),
      'SendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.SendMessage,
          request_deserializer=chat__pb2.Mensaje.FromString,
          response_serializer=chat__pb2.Nada.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ServerChat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
