# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mensajeria_pb2 as mensajeria__pb2


class HandShakeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HandShake = channel.unary_unary(
        '/HandShake/HandShake',
        request_serializer=mensajeria__pb2.Empty.SerializeToString,
        response_deserializer=mensajeria__pb2.IdRequest.FromString,
        )


class HandShakeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def HandShake(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HandShakeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HandShake': grpc.unary_unary_rpc_method_handler(
          servicer.HandShake,
          request_deserializer=mensajeria__pb2.Empty.FromString,
          response_serializer=mensajeria__pb2.IdRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HandShake', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MenuStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Menu = channel.unary_unary(
        '/Menu/Menu',
        request_serializer=mensajeria__pb2.Mensaje.SerializeToString,
        response_deserializer=mensajeria__pb2.Listado.FromString,
        )


class MenuServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Menu(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MenuServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Menu': grpc.unary_unary_rpc_method_handler(
          servicer.Menu,
          request_deserializer=mensajeria__pb2.Mensaje.FromString,
          response_serializer=mensajeria__pb2.Listado.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Menu', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Send = channel.unary_unary(
        '/Send/Send',
        request_serializer=mensajeria__pb2.Mensaje.SerializeToString,
        response_deserializer=mensajeria__pb2.Empty.FromString,
        )


class SendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Send(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Send': grpc.unary_unary_rpc_method_handler(
          servicer.Send,
          request_deserializer=mensajeria__pb2.Mensaje.FromString,
          response_serializer=mensajeria__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Send', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class ReceiveStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Receive = channel.unary_unary(
        '/Receive/Receive',
        request_serializer=mensajeria__pb2.Requester.SerializeToString,
        response_deserializer=mensajeria__pb2.Mensaje.FromString,
        )


class ReceiveServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Receive(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ReceiveServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Receive': grpc.unary_unary_rpc_method_handler(
          servicer.Receive,
          request_deserializer=mensajeria__pb2.Requester.FromString,
          response_serializer=mensajeria__pb2.Mensaje.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Receive', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
